# BCS Data Analysis Project

To frame our analysis, we must start with a concrete question to ground ourselves.
In this case, we're asking ourselves; So what's up with counter heals?
* how many do decks play on average?
* how do high performing decks relate to this average?
* how about low performing decks?

In order to answer this we'll need to:
* obtain HTML page for each decklog
* add each deck's info. into a data base (each card name and it's quantity)
* determine the names we want to know about
* query and graph the data

# Step 1 + 2
After a bit of wrangling, I've reworked these steps to start by scraping information about each event of the announcement page, so we can have information about the date of each event, and a second bit of scraping to get the link extension for each of those events off the event report page. 

Bushiroad might be weird with how their links are patterened or changed, as well as not maintaining event order between site pages, so it is wise to manually inspect the results of the scraping before feeding the results into our pipeline for data collection.

For more information about the scraping, and the schema of the table below, check out the Data Collection and Data Wrangling sections

In [ ]:
# BCS 25/26 Event locations
# These must manually be extracted from the bushiroad site, 
# https://en.cf-vanguard.com/event/bcs2526/
BASE_URL = "https://en.cf-vanguard.com/event/bcs2526/"

final_event_list=\
[
    ## ['illinois', 'Rosemont', 'NA', 'October 4, 2025'],
    ## ['mexico', 'Mexico', 'NA', 'November 8, 2025'],
    ## ['bcs2526-houston-tx', 'TX', 'NA', 'November 22, 2025'],
    ## ['bcs2526-california', 'LA', 'NA', 'December 6, 2025'],
    ## ['vancouver', 'BC', 'NA', 'January 10, 2026'],
    ## ['argentina', 'Argentina', 'NA', 'January 17, 2026'],
    ## ['duluth', 'Duluth', 'NA', 'January 17, 2026'],
    ## ['puerto-rico', 'Puerto Rico', 'NA', 'January 24, 2026'],
    
    ## The link will need testing
    # ['toronto-ca', 'Toronto', 'NA', 'February 14, 2026'],
    # ['san-jose-cr', 'Costa Rica', 'NA', 'February 21, 2026'],
    # ['philadelphia-pa', 'Philadelphia', 'NA', 'March 21, 2026'],

    
    ## ['modling-austria', 'Austria', 'EU', 'November 15, 2025'],
    ## ['italy', 'Italy', 'EU', 'December 13, 2025'],
    ## ['spain', 'Spain', 'EU', 'January 3, 2026'],
    ## ['france', 'France', 'EU', 'February 7, 2026'],
    
    ## These links will need testing
    # ['bochum', 'Germany', 'EU', 'February 21, 2026'],
    # ['greece', 'Greece', 'EU', 'March 7, 2026'],
    # ['manchester', 'United Kingdom', 'EU', 'March 21, 2026'],

    
    ## ['ho-chi-minh-city-vietnam', 'Vietnam', 'AO', 'November 2, 2025'],
    ## ['surabaya-indonesia', 'Indonesia', 'AO', 'November 16, 2025'],
    ## ['bcs2526-malaysia', 'Malaysia', 'AO', 'December 6, 2025'],
    ## ['manila', 'Philippines', 'AO', 'January 17, 2026'],
    ## ['singapore', 'Singapore', 'AO', 'January 24, 2026'],
    
    ## These links will need testing too
    # ['melbourne', 'Melbourne, Australia', 'AO', 'February 28, 2026'],
    # ['sydney', 'Sydney, Australia', 'AO', 'March 28, 2026'],
    # ['jakarta', 'Indonesia', 'AO', 'March 28, 2026']
]

In [ ]:

import os
import sys
# module_path = os.path.abspath(os.path.join('..'))
# if module_path not in sys.path:
#     sys.path.append(module_path)

from data_collection_pipeline import main as get_data
from data_collection_pipeline import *

print("This may take a few minutes for each event. Pleasse wait :  ^)")
for event in final_event_list:
    get_data(BASE_URL, event)
    # When finished, the data will be added to mongo db
    print('Fisnished: ', event[1])
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')

And just like that, we have ***loads*** of data in our data base. Time to get cracking.

Or well, it would be, but I ran into a few issues with the way the data was organized,
and so we did some data wrangling:
* converted rank and wins into ints for easier analysis, and updated the pipeline
* added information about when and where the event took place into the pipeline, so that data can be analyized over time
* added everything we have so far to one giant table as well

We did some webscrabing to get the date and location of every event for every region. Perhaps next year we can make a scraper to get the event specific URLS, so we can combine these 2 tables. Toss in a feature to automatically wake up a week after each event and look for the results, and we could have the makings of a sophisticated program on our hands. Let's not get too ahead of ourselves, though...


I decided that since there are still more events to do, I'd add these steps directly into function `get_data` above, so that this can automatically be applied on the events that were marked TODO at time of writing.

# Step 3: EDA

We're back from the wragling for a second shot at analysis, and I noticed that I couldn't find 'Two Of Us, Rhyme' in any decks. I felt like that card should have been included, so let's keep that in our minds moving forward, now that we can explore every event at once. Sureley one person had to play her, right?

Hmmm... How do winrates for bosses look over time? that could be interesting.

In [ ]:
EVENT = 'duluth'
HEALS = [
    "Stealth Fiend, Amaviera",
    "Incorruptible Holy Light, Eufha",
    "Lady Healer of the Creaking World",
    "Invigorate Sage",
    "Zypsophilia Fairy, Asher",
    "Two Of Us, Rhyme",
]
DRAWS = [
    'Flare Veil Dragon',
    'Rouse Wildmaster, Riley',
    'Ameliorate Connector',
    'Protection Magic, Prorobi',
    'Serene Maiden, Lena',
    'Transparent Snowy Night, Beretoi',
]

In [2]:
from pymongo import MongoClient

# Connect to MongoDB
username = 'sjmichael17_db_user'
password = 'rVtL43eBjseB5XkS' # plz don't hack me bro ;-;
cluster_address = 'bcsproto.peazuyx.mongodb.net/?appName=BCSproto'

client = MongoClient(f'mongodb+srv://{username}:{password}@{cluster_address}')

db = client['main_table']
collection = db['test']

In [9]:
import pandas as pd

In [10]:
# Aggregate wins across the collection: total, average, and document count.
pipeline = [
	{'$group': {
		'_id': None,
		'total_wins': {'$sum': '$wins'},
		'avg_wins': {'$avg': '$wins'},
		'count': {'$sum': 1}
	}}
]

result = list(collection.aggregate(pipeline))
result

[{'_id': None,
  'total_wins': 12594,
  'avg_wins': 3.0172496406324867,
  'count': 4174}]

## How big was each event?

In [43]:
loc_pipe = [
    {'$group': {
        '_id': '$location',
        'total_players': {'$sum': 1}
    }}
]

result = list(collection.aggregate(loc_pipe))
result.sort(key=lambda x: x['total_players'], reverse=True)
result

[{'_id': 'Duluth', 'total_players': 504},
 {'_id': 'LA', 'total_players': 489},
 {'_id': 'Philippines', 'total_players': 441},
 {'_id': 'TX', 'total_players': 338},
 {'_id': 'Rosemont', 'total_players': 307},
 {'_id': 'Malaysia', 'total_players': 294},
 {'_id': 'Singapore', 'total_players': 279},
 {'_id': 'France', 'total_players': 213},
 {'_id': 'Vietnam', 'total_players': 198},
 {'_id': 'BC', 'total_players': 193},
 {'_id': 'Indonesia', 'total_players': 184},
 {'_id': 'Austria', 'total_players': 164},
 {'_id': 'Mexico', 'total_players': 163},
 {'_id': 'Italy', 'total_players': 149},
 {'_id': 'Argentina', 'total_players': 100},
 {'_id': 'Puerto Rico', 'total_players': 86},
 {'_id': 'Spain', 'total_players': 72}]

In [89]:
pipeline = [
]

result = list(collection.find({
    "wins": {"$gt": 5}
}))
df= pd.DataFrame(result)
df.drop(columns=['_id'], inplace=True)
df.nation.unique()

array(['Dark States', 'Dragon Empire', 'Keter Sanctuary', 'Brandt Gate',
       'Stoicheia', 'Buddyfight', 'Lyrical Monasterio', 'BanG Dream!', ''],
      dtype=object)

In [13]:

df.describe()

             rank        wins
count  362.000000  362.000000
mean    20.002762    7.022099
std     21.254493    1.318758
min      1.000000    6.000000
25%      6.000000    6.000000
50%     12.000000    7.000000
75%     24.000000    8.000000
max     91.000000   13.000000

Max of 91? That seems wrong... but after some fact checking, it's true! After some inspection, I beleive they must have played an additional round of swiss.

This leaves me a bit unsure how to handle this event. 
I don't want to drop it completely, but it makes the cut of 6 wins less meaningful.

I feel that, at least for now, we'll proceed without it, without going so far as to drop it from our database

In [58]:
dff = df[df['location'] != 'Philippines']
dff.describe()

             rank        wins
count  271.000000  271.000000
mean    11.273063    7.077491
std      8.196158    1.290094
min      1.000000    6.000000
25%      5.000000    6.000000
50%      9.000000    7.000000
75%     16.000000    8.000000
max     36.000000   11.000000

Bwah, removing the third largest event probably isn't good for us in the end. How about we subract 1 win from each player, so that useful for analysis on higher ranking decks. This could cause problems when analysising lower performing decks later, so we'll need to put a pin in this metaphorically,

In [56]:
df_phil = df[df['location'] == 'Philippines']
df_phil['wins'] = df_phil['wins'] - 1
df_phil = df_phil[df_phil['wins'] > 5]
df_phil.describe()

/var/folders/11/sqv42t4x0qx5nnrnmm9mfm3r0000gn/T/ipykernel_1032/384307230.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_phil['wins'] = df_phil['wins'] - 1

            rank       wins
count  38.000000  38.000000
mean   19.500000   7.052632
std    11.113055   1.487740
min     1.000000   6.000000
25%    10.250000   6.000000
50%    19.500000   6.500000
75%    28.750000   7.000000
max    38.000000  12.000000

In [62]:
dfF = pd.concat([dff, df_phil], ignore_index=True)
dfF.describe()

             rank        wins
count  309.000000  309.000000
mean    12.284790    7.074434
std      9.002694    1.313378
min      1.000000    6.000000
25%      5.000000    6.000000
50%     10.000000    7.000000
75%     18.000000    8.000000
max     38.000000   12.000000

In [66]:
from os import path
# it could be wise to save this for later
dfF.to_json(path.join('/Users/admin/BCSdata/BCSanalysis/.json','ToppingDecks.json'), orient='records')

In [153]:
# lets test its loading for a sanity check
df2 = pd.read_json(path.join('/Users/admin/BCSdata/BCSanalysis/.json','ToppingDecks.json'), orient='records')
# df2 = df2.transpose()
df2.head()

,rank,name,boss,wins,nation,decklog,deck,location,region,date
0,1,Champion,"Sugary and Scary Land, Heartluru",11,Dark States,2FJ64,"{'RideDeck': {'Sugary and Scary Land, Heartlur...",Rosemont,NA,2025-10-04
1,3,Champion,"Fated One of Zero, Blangdmire",10,Dark States,546KJ,"{'RideDeck': {'Fated One of Zero, Blangdmire':...",Rosemont,NA,2025-10-04
2,6,BigDaddyBrie,"Sugary and Scary Land, Heartluru",8,Dark States,741C4,"{'RideDeck': {'Sugary and Scary Land, Heartlur...",Rosemont,NA,2025-10-04
3,7,Saaram,"Sealed Blaze of Arbitration, Bavsargra Aksayya",8,Dragon Empire,5JGCY,"{'RideDeck': {'Sealed Blaze of Arbitration, Ba...",Rosemont,NA,2025-10-04
4,10,Braceland,"Sealed Blaze of Arbitration, Bavsargra Aksayya",7,Dragon Empire,Z2WC,"{'RideDeck': {'Sealed Blaze of Arbitration, Ba...",Rosemont,NA,2025-10-04

## Next Up, the Mystery of Rhyme
nvm jk lol. Malaysia? I found then had no nations information for that event, so we'll need to invesigate deeper

In [ ]:
name = "Two Of Us, Rhyme"
# df2 = df2[df2['nation'] == 'Lyrical Monasterio']
df_mal = df2[df2['location'] == 'Malaysia']
df_mal.head()

,rank,name,boss,wins,nation,decklog,deck,location,region,date
218,2,Champion,"Sugary and Scary Land, Heartluru",9,,5F15K,"{'RideDeck': {'Sugary and Scary Land, Heartlur...",Malaysia,AO,2025-12-06
219,3,Champion,"Rewrite the Star, Vyrgilla",9,,6HF8D,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Malaysia,AO,2025-12-06
220,4,Ben Chan,"Rewrite the Star, Vyrgilla",8,,5AP89,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Malaysia,AO,2025-12-06
221,8,Yuuz,"Sealed Blaze of Arbitration, Bavsargra Aksayya",7,,443JM,"{'RideDeck': {'Sealed Blaze of Arbitration, Ba...",Malaysia,AO,2025-12-06
222,18,«Remy1ch1»,"Rewrite the Star, Vyrgilla",6,,56VXT,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Malaysia,AO,2025-12-06

Hm, I noticed the malaysian event ended up with some issues with the nation info. It seems just the flag was poste in that column for that event in particular.
For future analysis of nation information, this event either needs to be disregarded, or the data will need to be 'wrangled'.

In [ ]:
df_mal['boss'].unique()

array(['Sugary and Scary Land, Heartluru', 'Rewrite the Star, Vyrgilla',
       'Sealed Blaze of Arbitration, Bavsargra Aksayya',
       'Omniscience Regalia, Minerva',
       'Keeper of the Moon Gate, Veissrugr', 'Fountain of Knowledge, Eva'],
      dtype=object)

In [181]:
nations = {
    "Sealed Blaze of Arbitration, Bavsargra Aksayya": "Dragon Empire",
    "Rewrite the Star, Vyrgilla": "Dragon Empire",
    "Sugary and Scary Land, Heartluru": "Dark States",
    "Omniscience Regalia, Minerva": "Keter Sanctuary",
    "Keeper of the Moon Gate, Veissrugr": "Brandt Gate",
    "Fountain of Knowledge, Eva": "Brandt Gate"
}
for i, row in df_mal.iterrows():
   df_mal.loc[i, 'nation'] = nations[row.boss]

df_mal.head()

,rank,name,boss,wins,nation,decklog,deck,location,region,date
218,2,Champion,"Sugary and Scary Land, Heartluru",9,Dark States,5F15K,"{'RideDeck': {'Sugary and Scary Land, Heartlur...",Malaysia,AO,2025-12-06
219,3,Champion,"Rewrite the Star, Vyrgilla",9,Dragon Empire,6HF8D,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Malaysia,AO,2025-12-06
220,4,Ben Chan,"Rewrite the Star, Vyrgilla",8,Dragon Empire,5AP89,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Malaysia,AO,2025-12-06
221,8,Yuuz,"Sealed Blaze of Arbitration, Bavsargra Aksayya",7,Dragon Empire,443JM,"{'RideDeck': {'Sealed Blaze of Arbitration, Ba...",Malaysia,AO,2025-12-06
222,18,«Remy1ch1»,"Rewrite the Star, Vyrgilla",6,Dragon Empire,56VXT,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Malaysia,AO,2025-12-06

In [184]:
df2.iloc[df_mal.index] = df_mal
df2.nation.unique()

array(['Dark States', 'Dragon Empire', 'Keter Sanctuary', 'Brandt Gate',
       'Stoicheia', 'Buddyfight', 'Lyrical Monasterio', 'BanG Dream!'],
      dtype=object)

Excellent! An emptry string no longer appears in the nation column of the dataframe. Let's quickly save these changes.

In [185]:
df2.to_json(path.join('/Users/admin/BCSdata/BCSanalysis/.json','ToppingDecks.json'), orient='records')

Ok, Now with the Malaysia situation handled, we can return our focus to Rhyme. 
I recall from some early analysis that she didn't appear in my search when I expected her to, but I've found her as expected in some new searches. Let's do the analysis of heals starting with her, because we may kill 2 birds with one stone. 

We'll need to be very particular about the way we index into our decklists. They're;
* in the dataframe under the deck column
* are stored as a dictionary of 3 deck dictionaries;
    * RideDeck
    * MainDeck
    * GDeck
* Each of these deck dicts have the card name as the key, and the quantity played as the value

In [199]:
# Let's start with a helper function that kind find out if a card is in a deck
def card_is_in_deck(decks_dict, card_name, deck='MainDeck'):
    return card_name in decks_dict[deck]

def card_count_in_deck(decks_dict, card_name, deck='MainDeck'):
    return decks_dict[deck].get(card_name, 0)

In [212]:
name = "Two Of Us, Rhyme"
dfLyrical = df2[df2['nation'] == 'Lyrical Monasterio']
dfLyrical.boss.unique()
dfLyrical['count'] = dfLyrical.deck.apply(lambda deck: card_count_in_deck(deck, name))
dfLyrical.sort_values('count', inplace=True)
dfLyrical.head(13)

/var/folders/11/sqv42t4x0qx5nnrnmm9mfm3r0000gn/T/ipykernel_1032/2360167025.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfLyrical['count'] = dfLyrical.deck.apply(lambda deck: card_count_in_deck(deck, name))
/var/folders/11/sqv42t4x0qx5nnrnmm9mfm3r0000gn/T/ipykernel_1032/2360167025.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfLyrical.sort_values('count', inplace=True)

,rank,name,boss,wins,nation,decklog,deck,location,region,date,count
209,12,Hype n Play – Tama,"Astesice△Live, Kairi",6,Lyrical Monasterio,5VQLZ,"{'RideDeck': {'Astesice△Live, Kairi': 1, 'Top ...",Indonesia,AO,2025-11-16,1
289,25,Chunkie,"Fated One of Ever-changing, Krysrain Cadenza",6,Lyrical Monasterio,4XCBM,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Philippines,AO,2026-01-17,1
196,9,Đặng Gia Phú,"Astesice△Live, Kairi",6,Lyrical Monasterio,3Q5QR,"{'RideDeck': {'Astesice△Live, Kairi': 1, 'Top ...",Vietnam,AO,2025-11-02,1
91,8,Overlady Alicia,"Fated One of Ever-changing, Krysrain Cadenza",6,Lyrical Monasterio,6SPX5,"{'RideDeck': {'Fated One of Ever-changing, Kry...",BC,NA,2026-01-10,2
123,20,Kasmania,"Fated One of Ever-changing, Krysrain Cadenza",6,Lyrical Monasterio,4HEUK,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Duluth,NA,2026-01-17,2
95,7,Adrian Barber,"Fated One of Ever-changing, Krysrain Cadenza",7,Lyrical Monasterio,3X3AT,"{'RideDeck': {'Fated One of Ever-changing, Kry...",BC,NA,2026-01-10,2
98,6,WCJ HerLilTsundere,"Fated One of Ever-changing, Krysrain Cadenza",7,Lyrical Monasterio,235DM,"{'RideDeck': {'Fated One of Ever-changing, Kry...",BC,NA,2026-01-10,2
117,4,Noir’s Legacy,"Fated One of Ever-changing, Krysrain Cadenza",9,Lyrical Monasterio,1EBAK,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Duluth,NA,2026-01-17,2
308,37,D’ Original Budol,"Fated One of Ever-changing, Krysrain Cadenza",6,Lyrical Monasterio,4KARR,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Philippines,AO,2026-01-17,2
300,3,Champion,"Fated One of Ever-changing, Krysrain Cadenza",10,Lyrical Monasterio,7N2MH,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Philippines,AO,2026-01-17,2
108,7,Martinez,"Fated One of Ever-changing, Krysrain Cadenza",6,Lyrical Monasterio,2JU6T,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Argentina,NA,2026-01-17,3
128,1,Champion,"Fated One of Ever-changing, Krysrain Cadenza",10,Lyrical Monasterio,5D5V9,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Duluth,NA,2026-01-17,4
143,3,Champion,"Fated One of Ever-changing, Krysrain Cadenza",7,Lyrical Monasterio,6ZHV5,"{'RideDeck': {'Fated One of Ever-changing, Kry...",Puerto Rico,NA,2026-01-24,4

In [213]:
dfLyrical.describe()

            rank       wins                           date      count
count  13.000000  13.000000                             13  13.000000
mean   10.923077   7.076923  2026-01-05 07:23:04.615384576   2.153846
min     1.000000   6.000000            2025-11-02 00:00:00   1.000000
25%     4.000000   6.000000            2026-01-10 00:00:00   2.000000
50%     7.000000   6.000000            2026-01-17 00:00:00   2.000000
75%    12.000000   7.000000            2026-01-17 00:00:00   2.000000
max    37.000000  10.000000            2026-01-24 00:00:00   4.000000
std    10.412025   1.552500                            NaN   0.987096

{WOP POINT}

This is the results from some prelimiary heal type analysis

In [ ]:

"""
brandt
2.25
2.6
3.260869565217391
1.5
5

DE
2.652173913043478
3.0833333333333335
3.7142857142857144
4.5
4

DS
2.090909090909091
1.5
3.3157894736842106
2.5
3.1818181818181817

Lyrical bugged???

Stoi
2.1153846153846154
2.5714285714285716
2.5238095238095237
4.2
3.5

Keter
1.5
2.2857142857142856
2.875
2.6
2.5
"""

"""
Notes:
for every nation, playing 0 counter heals lowered the win rate to below the nations average.
    Playing 2 leads to better than average results,
except for stoi, who have better than average results for player 3+
Every nation, except brandt, has the best performing count at less than 4.
    It seems 2/3 should be good, unless you're brandt gate.
    Leaning twords 3 rn, since the brandt issue may be an outlier, and the others show decent growth.
        2 may be a bit more safe, but they're both better than 0, bar brandt gate.

Lyrical didn't turn up results for Rhyme... which is cause for concearn and investigation.
The next questions I have;
    How does the precence of draws affect things?
    How does the boss interact with heal stats?
    
"""