During analysis, I noticed to large issues with our data set:
* The Philippines event had an extra round
* The Malaysian event didn't supply nation textual information on the site

# Part 0

Don't run these first two code blocks here, or their output will be lost.

```
result = list(collection.find({
    "wins": {"$gt": 5}
}))
df= pd.DataFrame(result)
df.drop(columns=['_id'], inplace=True)
# Let's inspect our dataframe for posterity
df.nation.unique()
```

array(['Dark States', 'Dragon Empire', 'Keter Sanctuary', 'Brandt Gate',
       'Stoicheia', 'Buddyfight', 'Lyrical Monasterio', 'BanG Dream!', ''],
      dtype=object)

```
df.describe()
```


          rank 	        wins
count	362.000000	362.000000
mean	20.002762	7.022099
std	21.254493	1.318758
min	1.000000	6.000000
25%	6.000000	6.000000
50%	12.000000	7.000000
75%	24.000000	8.000000
max	91.000000	13.000000

The above are copied cells from the data analysis notebook, showing the issue of `''` in the list of nations, and the max win being 91.
The cells that isolated this issue were overwritten and covnerted into cells that solved the issue on a data frame, so for verification, at the end of this notebook, we should ensure that this issues no longer remain with the data when writing to the databases.

Now that we have our groundwork lined up, we still need to get our imports, and establish our DB connection.

In [ ]:

import db_operations

import pandas as pd

In [ ]:
# # Connect to MongoDB
# username = 'sjmichael17_db_user'
# password = 'rVtL43eBjseB5XkS' # plz don't hack me bro ;-;
# cluster_address = 'bcsproto.peazuyx.mongodb.net/?appName=BCSproto'

# client = MongoClient(f'mongodb+srv://{username}:{password}@{cluster_address}')

# db = client['main_table']
# main_collection = db['test']

# Part 1: Accounting the Extra Round
Since there was an extra round in the Philippines, it seemed most apporoprite to keep things in line with the other data, to reduce each player's win count by one for that event, and ensureing the value still 'min's out at 0.

In [5]:
# pipeline = [
# 	{'$group': {
# 		'_id': None,
# 		'total_wins': {'$sum': '$wins'},
# 		'avg_wins': {'$avg': '$wins'},
# 		'count': {'$sum': 1}
# 	}}
# ]

In [ ]:
# main_collection.delete_many({"location": "0"})
# main_collection.delete_many({"location": "Philippines"})
# manila_collection = client['JSONproto']["manila"]
# new_manila = manila_collection.find({})
# main_collection.insert_many(new_manila)

InsertManyResult([ObjectId('699e52775413ba5d3130e0b0'), ObjectId('699e52775413ba5d3130e0b1'), ObjectId('699e52775413ba5d3130e0b2'), ObjectId('699e52775413ba5d3130e0b3'), ObjectId('699e52775413ba5d3130e0b4'), ObjectId('699e52775413ba5d3130e0b5'), ObjectId('699e52775413ba5d3130e0b6'), ObjectId('699e52775413ba5d3130e0b7'), ObjectId('699e52775413ba5d3130e0b8'), ObjectId('699e52775413ba5d3130e0b9'), ObjectId('699e52775413ba5d3130e0ba'), ObjectId('699e52775413ba5d3130e0bb'), ObjectId('699e52775413ba5d3130e0bc'), ObjectId('699e52775413ba5d3130e0bd'), ObjectId('699e52775413ba5d3130e0be'), ObjectId('699e52775413ba5d3130e0bf'), ObjectId('699e52775413ba5d3130e0c0'), ObjectId('699e52775413ba5d3130e0c1'), ObjectId('699e52775413ba5d3130e0c2'), ObjectId('699e52775413ba5d3130e0c3'), ObjectId('699e52775413ba5d3130e0c4'), ObjectId('699e52775413ba5d3130e0c5'), ObjectId('699e52775413ba5d3130e0c6'), ObjectId('699e52775413ba5d3130e0c7'), ObjectId('699e52775413ba5d3130e0c8'), ObjectId('699e52775413ba5d3130e0c9'), ObjectId('699e52775413ba5d3130e0ca'), ObjectId('699e52775413ba5d3130e0cb'), ObjectId('699e52775413ba5d3130e0cc'), ObjectId('699e52775413ba5d3130e0cd'), ObjectId('699e52775413ba5d3130e0ce'), ObjectId('699e52775413ba5d3130e0cf'), ObjectId('699e52775413ba5d3130e0d0'), ObjectId('699e52775413ba5d3130e0d1'), ObjectId('699e52775413ba5d3130e0d2'), ObjectId('699e52775413ba5d3130e0d3'), ObjectId('699e52775413ba5d3130e0d4'), ObjectId('699e52775413ba5d3130e0d5'), ObjectId('699e52775413ba5d3130e0d6'), ObjectId('699e52775413ba5d3130e0d7'), ObjectId('699e52775413ba5d3130e0d8'), ObjectId('699e52775413ba5d3130e0d9'), ObjectId('699e52775413ba5d3130e0da'), ObjectId('699e52775413ba5d3130e0db'), ObjectId('699e52775413ba5d3130e0dc'), ObjectId('699e52775413ba5d3130e0dd'), ObjectId('699e52775413ba5d3130e0de'), ObjectId('699e52775413ba5d3130e0df'), ObjectId('699e52775413ba5d3130e0e0'), ObjectId('699e52775413ba5d3130e0e1'), ObjectId('699e52775413ba5d3130e0e2'), ObjectId('699e52775413ba5d3130e0e3'), ObjectId('699e52775413ba5d3130e0e4'), ObjectId('699e52775413ba5d3130e0e5'), ObjectId('699e52775413ba5d3130e0e6'), ObjectId('699e52775413ba5d3130e0e7'), ObjectId('699e52775413ba5d3130e0e8'), ObjectId('699e52775413ba5d3130e0e9'), ObjectId('699e52775413ba5d3130e0ea'), ObjectId('699e52775413ba5d3130e0eb'), ObjectId('699e52775413ba5d3130e0ec'), ObjectId('699e52775413ba5d3130e0ed'), ObjectId('699e52775413ba5d3130e0ee'), ObjectId('699e52775413ba5d3130e0ef'), ObjectId('699e52775413ba5d3130e0f0'), ObjectId('699e52775413ba5d3130e0f1'), ObjectId('699e52775413ba5d3130e0f2'), ObjectId('699e52775413ba5d3130e0f3'), ObjectId('699e52775413ba5d3130e0f4'), ObjectId('699e52775413ba5d3130e0f5'), ObjectId('699e52775413ba5d3130e0f6'), ObjectId('699e52775413ba5d3130e0f7'), ObjectId('699e52775413ba5d3130e0f8'), ObjectId('699e52775413ba5d3130e0f9'), ObjectId('699e52775413ba5d3130e0fa'), ObjectId('699e52775413ba5d3130e0fb'), ObjectId('699e52775413ba5d3130e0fc'), ObjectId('699e52775413ba5d3130e0fd'), ObjectId('699e52775413ba5d3130e0fe'), ObjectId('699e52775413ba5d3130e0ff'), ObjectId('699e52775413ba5d3130e100'), ObjectId('699e52775413ba5d3130e101'), ObjectId('699e52775413ba5d3130e102'), ObjectId('699e52775413ba5d3130e103'), ObjectId('699e52775413ba5d3130e104'), ObjectId('699e52775413ba5d3130e105'), ObjectId('699e52775413ba5d3130e106'), ObjectId('699e52775413ba5d3130e107'), ObjectId('699e52775413ba5d3130e108'), ObjectId('699e52775413ba5d3130e109'), ObjectId('699e52775413ba5d3130e10a'), ObjectId('699e52775413ba5d3130e10b'), ObjectId('699e52775413ba5d3130e10c'), ObjectId('699e52775413ba5d3130e10d'), ObjectId('699e52775413ba5d3130e10e'), ObjectId('699e52775413ba5d3130e10f'), ObjectId('699e52775413ba5d3130e110'), ObjectId('699e52775413ba5d3130e111'), ObjectId('699e52775413ba5d3130e112'), ObjectId('699e52775413ba5d3130e113'), ObjectId('699e52775413ba5d3130e114'), ObjectId('699e52775413ba5d3130e115'), ObjectId('699e52775413ba5d3130e116'), ObjectId('699e52775413ba5d3130e117'), ObjectId('699e52775413ba5d3130e118'), ObjectId('699e52775413ba5d3130e119'), ObjectId('699e52775413ba5d3130e11a'), ObjectId('699e52775413ba5d3130e11b'), ObjectId('699e52775413ba5d3130e11c'), ObjectId('699e52775413ba5d3130e11d'), ObjectId('699e52775413ba5d3130e11e'), ObjectId('699e52775413ba5d3130e11f'), ObjectId('699e52775413ba5d3130e120'), ObjectId('699e52775413ba5d3130e121'), ObjectId('699e52775413ba5d3130e122'), ObjectId('699e52775413ba5d3130e123'), ObjectId('699e52775413ba5d3130e124'), ObjectId('699e52775413ba5d3130e125'), ObjectId('699e52775413ba5d3130e126'), ObjectId('699e52775413ba5d3130e127'), ObjectId('699e52775413ba5d3130e128'), ObjectId('699e52775413ba5d3130e129'), ObjectId('699e52775413ba5d3130e12a'), ObjectId('699e52775413ba5d3130e12b'), ObjectId('699e52775413ba5d3130e12c'), ObjectId('699e52775413ba5d3130e12d'), ObjectId('699e52775413ba5d3130e12e'), ObjectId('699e52775413ba5d3130e12f'), ObjectId('699e52775413ba5d3130e130'), ObjectId('699e52775413ba5d3130e131'), ObjectId('699e52775413ba5d3130e132'), ObjectId('699e52775413ba5d3130e133'), ObjectId('699e52775413ba5d3130e134'), ObjectId('699e52775413ba5d3130e135'), ObjectId('699e52775413ba5d3130e136'), ObjectId('699e52775413ba5d3130e137'), ObjectId('699e52775413ba5d3130e138'), ObjectId('699e52775413ba5d3130e139'), ObjectId('699e52775413ba5d3130e13a'), ObjectId('699e52775413ba5d3130e13b'), ObjectId('699e52775413ba5d3130e13c'), ObjectId('699e52775413ba5d3130e13d'), ObjectId('699e52775413ba5d3130e13e'), ObjectId('699e52775413ba5d3130e13f'), ObjectId('699e52775413ba5d3130e140'), ObjectId('699e52775413ba5d3130e141'), ObjectId('699e52775413ba5d3130e142'), ObjectId('699e52775413ba5d3130e143'), ObjectId('699e52775413ba5d3130e144'), ObjectId('699e52775413ba5d3130e145'), ObjectId('699e52775413ba5d3130e146'), ObjectId('699e52775413ba5d3130e147'), ObjectId('699e52775413ba5d3130e148'), ObjectId('699e52775413ba5d3130e149'), ObjectId('699e52775413ba5d3130e14a'), ObjectId('699e52775413ba5d3130e14b'), ObjectId('699e52775413ba5d3130e14c'), ObjectId('699e52775413ba5d3130e14d'), ObjectId('699e52775413ba5d3130e14e'), ObjectId('699e52775413ba5d3130e14f'), ObjectId('699e52775413ba5d3130e150'), ObjectId('699e52775413ba5d3130e151'), ObjectId('699e52775413ba5d3130e152'), ObjectId('699e52775413ba5d3130e153'), ObjectId('699e52775413ba5d3130e154'), ObjectId('699e52775413ba5d3130e155'), ObjectId('699e52775413ba5d3130e156'), ObjectId('699e52775413ba5d3130e157'), ObjectId('699e52775413ba5d3130e158'), ObjectId('699e52775413ba5d3130e159'), ObjectId('699e52775413ba5d3130e15a'), ObjectId('699e52775413ba5d3130e15b'), ObjectId('699e52775413ba5d3130e15c'), ObjectId('699e52775413ba5d3130e15d'), ObjectId('699e52775413ba5d3130e15e'), ObjectId('699e52775413ba5d3130e15f'), ObjectId('699e52775413ba5d3130e160'), ObjectId('699e52775413ba5d3130e161'), ObjectId('699e52775413ba5d3130e162'), ObjectId('699e52775413ba5d3130e163'), ObjectId('699e52775413ba5d3130e164'), ObjectId('699e52775413ba5d3130e165'), ObjectId('699e52775413ba5d3130e166'), ObjectId('699e52775413ba5d3130e167'), ObjectId('699e52775413ba5d3130e168'), ObjectId('699e52775413ba5d3130e169'), ObjectId('699e52775413ba5d3130e16a'), ObjectId('699e52775413ba5d3130e16b'), ObjectId('699e52775413ba5d3130e16c'), ObjectId('699e52775413ba5d3130e16d'), ObjectId('699e52775413ba5d3130e16e'), ObjectId('699e52775413ba5d3130e16f'), ObjectId('699e52775413ba5d3130e170'), ObjectId('699e52775413ba5d3130e171'), ObjectId('699e52775413ba5d3130e172'), ObjectId('699e52775413ba5d3130e173'), ObjectId('699e52775413ba5d3130e174'), ObjectId('699e52775413ba5d3130e175'), ObjectId('699e52775413ba5d3130e176'), ObjectId('699e52775413ba5d3130e177'), ObjectId('699e52775413ba5d3130e178'), ObjectId('699e52775413ba5d3130e179'), ObjectId('699e52775413ba5d3130e17a'), ObjectId('699e52775413ba5d3130e17b'), ObjectId('699e52775413ba5d3130e17c'), ObjectId('699e52775413ba5d3130e17d'), ObjectId('699e52775413ba5d3130e17e'), ObjectId('699e52775413ba5d3130e17f'), ObjectId('699e52775413ba5d3130e180'), ObjectId('699e52775413ba5d3130e181'), ObjectId('699e52775413ba5d3130e182'), ObjectId('699e52775413ba5d3130e183'), ObjectId('699e52775413ba5d3130e184'), ObjectId('699e52775413ba5d3130e185'), ObjectId('699e52775413ba5d3130e186'), ObjectId('699e52775413ba5d3130e187'), ObjectId('699e52775413ba5d3130e188'), ObjectId('699e52775413ba5d3130e189'), ObjectId('699e52775413ba5d3130e18a'), ObjectId('699e52775413ba5d3130e18b'), ObjectId('699e52775413ba5d3130e18c'), ObjectId('699e52775413ba5d3130e18d'), ObjectId('699e52775413ba5d3130e18e'), ObjectId('699e52775413ba5d3130e18f'), ObjectId('699e52775413ba5d3130e190'), ObjectId('699e52775413ba5d3130e191'), ObjectId('699e52775413ba5d3130e192'), ObjectId('699e52775413ba5d3130e193'), ObjectId('699e52775413ba5d3130e194'), ObjectId('699e52775413ba5d3130e195'), ObjectId('699e52775413ba5d3130e196'), ObjectId('699e52775413ba5d3130e197'), ObjectId('699e52775413ba5d3130e198'), ObjectId('699e52775413ba5d3130e199'), ObjectId('699e52775413ba5d3130e19a'), ObjectId('699e52775413ba5d3130e19b'), ObjectId('699e52775413ba5d3130e19c'), ObjectId('699e52775413ba5d3130e19d'), ObjectId('699e52775413ba5d3130e19e'), ObjectId('699e52775413ba5d3130e19f'), ObjectId('699e52775413ba5d3130e1a0'), ObjectId('699e52775413ba5d3130e1a1'), ObjectId('699e52775413ba5d3130e1a2'), ObjectId('699e52775413ba5d3130e1a3'), ObjectId('699e52775413ba5d3130e1a4'), ObjectId('699e52775413ba5d3130e1a5'), ObjectId('699e52775413ba5d3130e1a6'), ObjectId('699e52775413ba5d3130e1a7'), ObjectId('699e52775413ba5d3130e1a8'), ObjectId('699e52775413ba5d3130e1a9'), ObjectId('699e52775413ba5d3130e1aa'), ObjectId('699e52775413ba5d3130e1ab'), ObjectId('699e52775413ba5d3130e1ac'), ObjectId('699e52775413ba5d3130e1ad'), ObjectId('699e52775413ba5d3130e1ae'), ObjectId('699e52775413ba5d3130e1af'), ObjectId('699e52775413ba5d3130e1b0'), ObjectId('699e52775413ba5d3130e1b1'), ObjectId('699e52775413ba5d3130e1b2'), ObjectId('699e52775413ba5d3130e1b3'), ObjectId('699e52775413ba5d3130e1b4'), ObjectId('699e52775413ba5d3130e1b5'), ObjectId('699e52775413ba5d3130e1b6'), ObjectId('699e52775413ba5d3130e1b7'), ObjectId('699e52775413ba5d3130e1b8'), ObjectId('699e52775413ba5d3130e1b9'), ObjectId('699e52775413ba5d3130e1ba'), ObjectId('699e52775413ba5d3130e1bb'), ObjectId('699e52775413ba5d3130e1bc'), ObjectId('699e52775413ba5d3130e1bd'), ObjectId('699e52775413ba5d3130e1be'), ObjectId('699e52775413ba5d3130e1bf'), ObjectId('699e52775413ba5d3130e1c0'), ObjectId('699e52775413ba5d3130e1c1'), ObjectId('699e52775413ba5d3130e1c2'), ObjectId('699e52775413ba5d3130e1c3'), ObjectId('699e52775413ba5d3130e1c4'), ObjectId('699e52775413ba5d3130e1c5'), ObjectId('699e52775413ba5d3130e1c6'), ObjectId('699e52775413ba5d3130e1c7'), ObjectId('699e52775413ba5d3130e1c8'), ObjectId('699e52775413ba5d3130e1c9'), ObjectId('699e52775413ba5d3130e1ca'), ObjectId('699e52775413ba5d3130e1cb'), ObjectId('699e52775413ba5d3130e1cc'), ObjectId('699e52775413ba5d3130e1cd'), ObjectId('699e52775413ba5d3130e1ce'), ObjectId('699e52775413ba5d3130e1cf'), ObjectId('699e52775413ba5d3130e1d0'), ObjectId('699e52775413ba5d3130e1d1'), ObjectId('699e52775413ba5d3130e1d2'), ObjectId('699e52775413ba5d3130e1d3'), ObjectId('699e52775413ba5d3130e1d4'), ObjectId('699e52775413ba5d3130e1d5'), ObjectId('699e52775413ba5d3130e1d6'), ObjectId('699e52775413ba5d3130e1d7'), ObjectId('699e52775413ba5d3130e1d8'), ObjectId('699e52775413ba5d3130e1d9'), ObjectId('699e52775413ba5d3130e1da'), ObjectId('699e52775413ba5d3130e1db'), ObjectId('699e52775413ba5d3130e1dc'), ObjectId('699e52775413ba5d3130e1dd'), ObjectId('699e52775413ba5d3130e1de'), ObjectId('699e52775413ba5d3130e1df'), ObjectId('699e52775413ba5d3130e1e0'), ObjectId('699e52775413ba5d3130e1e1'), ObjectId('699e52775413ba5d3130e1e2'), ObjectId('699e52775413ba5d3130e1e3'), ObjectId('699e52775413ba5d3130e1e4'), ObjectId('699e52775413ba5d3130e1e5'), ObjectId('699e52775413ba5d3130e1e6'), ObjectId('699e52775413ba5d3130e1e7'), ObjectId('699e52775413ba5d3130e1e8'), ObjectId('699e52775413ba5d3130e1e9'), ObjectId('699e52775413ba5d3130e1ea'), ObjectId('699e52775413ba5d3130e1eb'), ObjectId('699e52775413ba5d3130e1ec'), ObjectId('699e52775413ba5d3130e1ed'), ObjectId('699e52775413ba5d3130e1ee'), ObjectId('699e52775413ba5d3130e1ef'), ObjectId('699e52775413ba5d3130e1f0'), ObjectId('699e52775413ba5d3130e1f1'), ObjectId('699e52775413ba5d3130e1f2'), ObjectId('699e52775413ba5d3130e1f3'), ObjectId('699e52775413ba5d3130e1f4'), ObjectId('699e52775413ba5d3130e1f5'), ObjectId('699e52775413ba5d3130e1f6'), ObjectId('699e52775413ba5d3130e1f7'), ObjectId('699e52775413ba5d3130e1f8'), ObjectId('699e52775413ba5d3130e1f9'), ObjectId('699e52775413ba5d3130e1fa'), ObjectId('699e52775413ba5d3130e1fb'), ObjectId('699e52775413ba5d3130e1fc'), ObjectId('699e52775413ba5d3130e1fd'), ObjectId('699e52775413ba5d3130e1fe'), ObjectId('699e52775413ba5d3130e1ff'), ObjectId('699e52775413ba5d3130e200'), ObjectId('699e52775413ba5d3130e201'), ObjectId('699e52775413ba5d3130e202'), ObjectId('699e52775413ba5d3130e203'), ObjectId('699e52775413ba5d3130e204'), ObjectId('699e52775413ba5d3130e205'), ObjectId('699e52775413ba5d3130e206'), ObjectId('699e52775413ba5d3130e207'), ObjectId('699e52775413ba5d3130e208'), ObjectId('699e52775413ba5d3130e209'), ObjectId('699e52775413ba5d3130e20a'), ObjectId('699e52775413ba5d3130e20b'), ObjectId('699e52775413ba5d3130e20c'), ObjectId('699e52775413ba5d3130e20d'), ObjectId('699e52775413ba5d3130e20e'), ObjectId('699e52775413ba5d3130e20f'), ObjectId('699e52775413ba5d3130e210'), ObjectId('699e52775413ba5d3130e211'), ObjectId('699e52775413ba5d3130e212'), ObjectId('699e52775413ba5d3130e213'), ObjectId('699e52775413ba5d3130e214'), ObjectId('699e52775413ba5d3130e215'), ObjectId('699e52775413ba5d3130e216'), ObjectId('699e52775413ba5d3130e217'), ObjectId('699e52775413ba5d3130e218'), ObjectId('699e52775413ba5d3130e219'), ObjectId('699e52775413ba5d3130e21a'), ObjectId('699e52775413ba5d3130e21b'), ObjectId('699e52775413ba5d3130e21c'), ObjectId('699e52775413ba5d3130e21d'), ObjectId('699e52775413ba5d3130e21e'), ObjectId('699e52775413ba5d3130e21f'), ObjectId('699e52775413ba5d3130e220'), ObjectId('699e52775413ba5d3130e221'), ObjectId('699e52775413ba5d3130e222'), ObjectId('699e52775413ba5d3130e223'), ObjectId('699e52775413ba5d3130e224'), ObjectId('699e52775413ba5d3130e225'), ObjectId('699e52775413ba5d3130e226'), ObjectId('699e52775413ba5d3130e227'), ObjectId('699e52775413ba5d3130e228'), ObjectId('699e52775413ba5d3130e229'), ObjectId('699e52775413ba5d3130e22a'), ObjectId('699e52775413ba5d3130e22b'), ObjectId('699e52775413ba5d3130e22c'), ObjectId('699e52775413ba5d3130e22d'), ObjectId('699e52775413ba5d3130e22e'), ObjectId('699e52775413ba5d3130e22f'), ObjectId('699e52775413ba5d3130e230'), ObjectId('699e52775413ba5d3130e231'), ObjectId('699e52775413ba5d3130e232'), ObjectId('699e52775413ba5d3130e233'), ObjectId('699e52775413ba5d3130e234'), ObjectId('699e52775413ba5d3130e235'), ObjectId('699e52775413ba5d3130e236'), ObjectId('699e52775413ba5d3130e237'), ObjectId('699e52775413ba5d3130e238'), ObjectId('699e52775413ba5d3130e239'), ObjectId('699e52775413ba5d3130e23a'), ObjectId('699e52775413ba5d3130e23b'), ObjectId('699e52775413ba5d3130e23c'), ObjectId('699e52775413ba5d3130e23d'), ObjectId('699e52775413ba5d3130e23e'), ObjectId('699e52775413ba5d3130e23f'), ObjectId('699e52775413ba5d3130e240'), ObjectId('699e52775413ba5d3130e241'), ObjectId('699e52775413ba5d3130e242'), ObjectId('699e52775413ba5d3130e243'), ObjectId('699e52775413ba5d3130e244'), ObjectId('699e52775413ba5d3130e245'), ObjectId('699e52775413ba5d3130e246'), ObjectId('699e52775413ba5d3130e247'), ObjectId('699e52775413ba5d3130e248'), ObjectId('699e52775413ba5d3130e249'), ObjectId('699e52775413ba5d3130e24a'), ObjectId('699e52775413ba5d3130e24b'), ObjectId('699e52775413ba5d3130e24c'), ObjectId('699e52775413ba5d3130e24d'), ObjectId('699e52775413ba5d3130e24e'), ObjectId('699e52775413ba5d3130e24f'), ObjectId('699e52775413ba5d3130e250'), ObjectId('699e52775413ba5d3130e251'), ObjectId('699e52775413ba5d3130e252'), ObjectId('699e52775413ba5d3130e253'), ObjectId('699e52775413ba5d3130e254'), ObjectId('699e52775413ba5d3130e255'), ObjectId('699e52775413ba5d3130e256'), ObjectId('699e52775413ba5d3130e257'), ObjectId('699e52775413ba5d3130e258'), ObjectId('699e52775413ba5d3130e259'), ObjectId('699e52775413ba5d3130e25a'), ObjectId('699e52775413ba5d3130e25b'), ObjectId('699e52775413ba5d3130e25c'), ObjectId('699e52775413ba5d3130e25d'), ObjectId('699e52775413ba5d3130e25e'), ObjectId('699e52775413ba5d3130e25f'), ObjectId('699e52775413ba5d3130e260'), ObjectId('699e52775413ba5d3130e261'), ObjectId('699e52775413ba5d3130e262'), ObjectId('699e52775413ba5d3130e263'), ObjectId('699e52775413ba5d3130e264'), ObjectId('699e52775413ba5d3130e265'), ObjectId('699e52775413ba5d3130e266'), ObjectId('699e52775413ba5d3130e267'), ObjectId('699e52775413ba5d3130e268')], acknowledged=True)

In [ ]:
# result = list(main_collection.find({
#     # "wins": {"$gt": 5}
# }))
# df= pd.DataFrame(result)
# df.drop(columns=['_id'], inplace=True)
# df.describe()
# df.nation.unique()

              rank         wins
count  4174.000000  4174.000000
mean    158.150934     3.017250
std     120.011010     1.977877
min       1.000000     0.000000
25%      62.000000     1.000000
50%     131.000000     3.000000
75%     231.000000     4.000000
max     504.000000    13.000000

In [ ]:
df_phil = db_operations.get_answer_from_table('main_table',
                                    'all_events',
                                    {'loacation':'Philippines'})

# Reduce each players wins by 1 to acoount for extra round
df_phil.loc[:, 'wins'] -= 1 
# Make sure players with negitive wins are set to 0
df_phil.loc[df_phil['wins'] == -1, 'wins'] = 0

df_fixed = df_phil
df_fixed.describe()

            rank        wins
count  441.00000  441.000000
mean   221.00000    2.575964
std    127.44999    2.179296
min      1.00000    0.000000
25%    111.00000    1.000000
50%    221.00000    2.000000
75%    331.00000    4.000000
max    441.00000   12.000000

# Part 2: Nation Mapping

In [ ]:

df_mal = db_operations.get_answer_from_table('main_table',
                                    'all_events',
                                    {'loacation':'Malaysia'})

df_mal.boss.unique()

array(['Sugary and Scary Land, Heartluru', 'Rewrite the Star, Vyrgilla',
       'Sealed Blaze of Arbitration, Bavsargra Aksayya',
       'Omniscience Regalia, Minerva',
       'Vampire Princess of Night Fog, Nightrose',
       'Future Force Possessor, Tasuku Ryuenji', 'Dragonic Overlord',
       'Aurora Battle Princess, Seraph Snow',
       'Destined King of Infinity, Levidras Empireo',
       'Fated One of Zero, Blangdmire',
       'Destined One of Scales, Aelquilibra',
       'Fountain of Knowledge, Eva', 'Keeper of the Moon Gate, Veissrugr',
       'Fated One of Unparalleled, Varga Dragres',
       'Destined One of Time, Liael=Odium', 'Oblivionis the Noble',
       'Quaking Ripple Monster, Eledglema',
       'Demonic Jewel Dragon Emperor, Drajeweled Magnus',
       'Galactic B-Hero, Stately Crozard',
       'Fated One of Miracles, Rezael',
       'Sylvan Horned Beast Emperor, Magnolia Patriarch',
       "Fated One of Guiding Star, Welstra 'Blitz Arms'",
       "Demon Stealth Dragon, Shiranui 'Oboro'",
       'PolyPhonicOverDrive, Artisaria',
       'Purgatory Dragon Deity, Favrneel',
       'Sword of the Nation, Bastion Accord',
       'Fated One of Ever-changing, Krysrain',
       'Direful Doll Master, Androld', 'Savior of the World, Kyoya Gaen',
       'Dragheart, Luard', 'Destined One of Exceedance, Impauldio',
       'Absolute Zero, Sagitta', 'Crying Heart, Tomori Takamatsu',
       'Argo Siren, Calliopeia', "Youthberk 'Skyfall Arms: Rebuild'",
       'Belgr the Skyruler', 'Pining Flower Maiden, Claudine',
       'Incandescent Lion, Blond Ezel', 'Cardinal Dominus, Orfist Regis',
       'Fated One of Taboo, Zorga Nadir',
       'One Who Guides Towards Paradise, Nannaclir',
       'Cloudwater Flitfoot Stealth Rogue, Shojodoji',
       'Hound Raiser, Aoi', 'Chakrabarthi Phoenix Dragon, Nirvana Jheva',
       'LèVre♡SœurS, Charmout', 'Sword Saint Knight Dragon, Gramgrace',
       "Dragonic Kaiser Vermillion 'THE BLOOD'",
       'Destined One of Supremacy, Lisciafael', 'Majesty Lord Blaster',
       'Super Dimensional Robo, Daiyusha', 'Brightest Dreamer, Lilfa',
       'Poison Knight of Silence Undercover, Mordalion',
       'Chronojet Dragon', 'Avaricious Demonic Dragon, Greedon',
       'Sword Saint Knight Dragon Emperor, Gramgrace Sieg',
       'Grand March of Full Bloom, Lianorn',
       "Blue Deathster, 'Skyrender' Avantgarda", 'Alter Ego Messiah',
       'Sing with Me, Loronerol', 'FL∀MMe-Glam, Rougia',
       'Scarlet Flame Marshal Dragon, Gandeeva', 'Juicy-Fruity, Tuarina',
       'Give the Whole World a Spark, Tetsuya Kurodake',
       'Legend of the Celestial Fury, Estacion',
       'Darkness-exposing Demon,  Black',
       "Aspiring 'Ninja-user of Justice', Zanya Kisaragi",
       'Fiery Immolation Dragon, Kotihblaze', 'Venatiol, Dhinbarada',
       'Astesice△Live, Kairi', 'Dragconnector, Grhyaundra',
       'Venerable, Stoeirhaja', 'Astesice, Kairi', 'Malwyrm, Sybilt'],
      dtype=object)

In [ ]:
df_mal.nation.unique()

array(['Dark States', 'Dragon Empire', 'Brandt Gate', 'Keter Sanctuary',
       'Stoicheia', 'Lyrical Monasterio', 'BanG Dream!', 'Buddyfight',
       'SHAMAN KING', 'Touken Ranbu'], dtype=object)

In [121]:
nations = [
    "Brandt Gate",            # 0
    "Dark States",            # 1
    "Dragon Empire",          # 2
    "Keter Sanctuary",        # 3
    "Stoicheia",              # 4
    "Lyrical Monasterio",     # 5
    "BanG Dream!",            # 6
    "SHAMAN KING",            # 7
    "Buddyfight",             # 8
    "Touken Ranbu"            # 9
]

In [122]:
bosses = {
    'Sugary and Scary Land, Heartluru': nations[1],
    'Rewrite the Star, Vyrgilla': nations[2],
    'Sealed Blaze of Arbitration, Bavsargra Aksayya': nations[2],
    'Omniscience Regalia, Minerva': nations[3],
    'Vampire Princess of Night Fog, Nightrose': nations[4],
    'Future Force Possessor, Tasuku Ryuenji': nations[8],
    'Dragonic Overlord': nations[2],
    'Aurora Battle Princess, Seraph Snow': nations[0],
    'Destined King of Infinity, Levidras Empireo': nations[4],
    'Fated One of Zero, Blangdmire': nations[1],
    'Destined One of Scales, Aelquilibra': nations[2],
    'Fountain of Knowledge, Eva': nations[0],
    'Keeper of the Moon Gate, Veissrugr': nations[0],
    'Fated One of Unparalleled, Varga Dragres': nations[2],
    'Destined One of Time, Liael=Odium': nations[1],
    'Oblivionis the Noble': nations[6],
    'Quaking Ripple Monster, Eledglema': nations[0],
    'Demonic Jewel Dragon Emperor, Drajeweled Magnus': nations[1],
    'Galactic B-Hero, Stately Crozard': nations[0],
    'Fated One of Miracles, Rezael': nations[3],
    'Sylvan Horned Beast Emperor, Magnolia Patriarch': nations[4],
    "Fated One of Guiding Star, Welstra 'Blitz Arms'": nations[0],
    "Demon Stealth Dragon, Shiranui 'Oboro'": nations[2],
    'PolyPhonicOverDrive, Artisaria': nations[5],
    'Purgatory Dragon Deity, Favrneel': nations[1],
    'Sword of the Nation, Bastion Accord': nations[3],
    'Fated One of Ever-changing, Krysrain': nations[5],
    'Direful Doll Master, Androld': nations[1],
    'Savior of the World, Kyoya Gaen': nations[8],
    'Dragheart, Luard': nations[3],
    'Destined One of Exceedance, Impauldio': nations[0],
    'Absolute Zero, Sagitta': nations[5],
    'Crying Heart, Tomori Takamatsu': nations[6],
    'Argo Siren, Calliopeia': nations[4],
    "Youthberk 'Skyfall Arms: Rebuild'": nations[3],
    'Belgr the Skyruler': nations[4],
    'Pining Flower Maiden, Claudine': nations[4],
    'Incandescent Lion, Blond Ezel': nations[3],
    'Cardinal Dominus, Orfist Regis': nations[0],
    'Fated One of Taboo, Zorga Nadir': nations[4],
    'One Who Guides Towards Paradise, Nannaclir': nations[4],
    'Cloudwater Flitfoot Stealth Rogue, Shojodoji': nations[2],
    'Hound Raiser, Aoi': nations[3],
    'Chakrabarthi Phoenix Dragon, Nirvana Jheva': nations[2],
    'LèVre♡SœurS, Charmout': nations[5],
    'Sword Saint Knight Dragon, Gramgrace': nations[3],
    "Dragonic Kaiser Vermillion 'THE BLOOD'": nations[2],
    'Destined One of Supremacy, Lisciafael': nations[5],
    'Majesty Lord Blaster': nations[3],
    'Super Dimensional Robo, Daiyusha': nations[0],
    'Brightest Dreamer, Lilfa': nations[5],
    'Poison Knight of Silence Undercover, Mordalion': nations[3],
    'Chronojet Dragon': nations[1],
    'Avaricious Demonic Dragon, Greedon': nations[1],
    'Sword Saint Knight Dragon Emperor, Gramgrace Sieg': nations[3],
    'Grand March of Full Bloom, Lianorn': nations[4],
    "Blue Deathster, 'Skyrender' Avantgarda": nations[0],
    'Alter Ego Messiah': nations[0],
    'Sing with Me, Loronerol': nations[5],
    'FL∀MMe-Glam, Rougia': nations[5],
    'Scarlet Flame Marshal Dragon, Gandeeva': nations[2],
    'Juicy-Fruity, Tuarina': nations[5],
    'Give the Whole World a Spark, Tetsuya Kurodake': nations[8],
    'Legend of the Celestial Fury, Estacion': nations[4],
    'Darkness-exposing Demon,  Black': nations[0],
    "Aspiring 'Ninja-user of Justice', Zanya Kisaragi": nations[8],
    'Fiery Immolation Dragon, Kotihblaze': nations[2],
    'Venatiol, Dhinbarada': nations[2],
    'Astesice△Live, Kairi': nations[5],
    'Dragconnector, Grhyaundra': nations[2],
    'Venerable, Stoeirhaja': nations[4],
    'Astesice, Kairi': nations[5],
    'Malwyrm, Sybilt': nations[2],
}

In [123]:

for i, row in df_mal.iterrows():
   df_mal.loc[i, 'nation'] = bosses[row.boss]

df_mal.nation.unique()

array(['Dark States', 'Dragon Empire', 'Keter Sanctuary', 'Stoicheia',
       'Buddyfight', 'Brandt Gate', 'BanG Dream!', 'Lyrical Monasterio'],
      dtype=object)

In [142]:
df_fixed.loc[df_mal.index, :] = df_mal
df_fixed.nation.unique()
df_fixed.describe()
# df_fixed.head()

              rank         wins
count  4174.000000  4174.000000
mean    158.150934     2.918304
std     120.011010     1.963673
min       1.000000     0.000000
25%      62.000000     1.000000
50%     131.000000     3.000000
75%     231.000000     4.000000
max     504.000000    12.000000

Looks like we got 'em all ^_^

# Part 3: Saving the Changes

TODO

I need to make a sort of 'transaction for the note book session, so I don't accidentially bork something up in develpment.
If the original database wasn't in memory still, I would have accidently droped the main collection, which would have problamatic to say the least.

In [ ]:
# Ran into an issue with 'set on a copy of a slice'
# So I need to reframe how we do the df prep

# df_phil = pd.DataFrame(df[df['location'] == 'Philippines'])
# df_mal  = pd.DataFrame(df[df['location'] == 'Malaysia'])

We're saving both sets of changes to the main table, but we're only going to move the malaysian nation changes to the individual table, and not the win adjustment for the Philippines.

I'd like to perserve the original win data somehow, but the missing nation informaiton doesn't need preserving.

In [ ]:
# main_collection.drop()
# main_collection.insert_many(df_fixed.to_dict(orient='records'))
payload = df_fixed.to_dict(orient='records')
db_operations.update_table('main_table', 'all_events', payload)


# ## df_phil.drop(columns=['_id'], inplace=True)
# phil_collection = client["JSONproto"]['manila']
# phil_collection.drop()
# phil_collection.insert_many(df_phil.to_dict(orient='records'))

# ## df_mal.drop(columns=['_id'], inplace=True)
# mal_collection = client["JSONproto"]['bcs2526-malaysia']
# mal_collection.drop()
# mal_collection.insert_many(df_mal.to_dict(orient='records'))

payload = df_mal.to_dict(orient='records')
db_operations.update_table('JSONproto', 'Malaysia', payload)

InsertManyResult([ObjectId('699e5d07d48520146b9dd5e9'), ObjectId('699e5d07d48520146b9dd5ea'), ObjectId('699e5d07d48520146b9dd5eb'), ObjectId('699e5d07d48520146b9dd5ec'), ObjectId('699e5d07d48520146b9dd5ed'), ObjectId('699e5d07d48520146b9dd5ee'), ObjectId('699e5d07d48520146b9dd5ef'), ObjectId('699e5d07d48520146b9dd5f0'), ObjectId('699e5d07d48520146b9dd5f1'), ObjectId('699e5d07d48520146b9dd5f2'), ObjectId('699e5d07d48520146b9dd5f3'), ObjectId('699e5d07d48520146b9dd5f4'), ObjectId('699e5d07d48520146b9dd5f5'), ObjectId('699e5d07d48520146b9dd5f6'), ObjectId('699e5d07d48520146b9dd5f7'), ObjectId('699e5d07d48520146b9dd5f8'), ObjectId('699e5d07d48520146b9dd5f9'), ObjectId('699e5d07d48520146b9dd5fa'), ObjectId('699e5d07d48520146b9dd5fb'), ObjectId('699e5d07d48520146b9dd5fc'), ObjectId('699e5d07d48520146b9dd5fd'), ObjectId('699e5d07d48520146b9dd5fe'), ObjectId('699e5d07d48520146b9dd5ff'), ObjectId('699e5d07d48520146b9dd600'), ObjectId('699e5d07d48520146b9dd601'), ObjectId('699e5d07d48520146b9dd602'), ObjectId('699e5d07d48520146b9dd603'), ObjectId('699e5d07d48520146b9dd604'), ObjectId('699e5d07d48520146b9dd605'), ObjectId('699e5d07d48520146b9dd606'), ObjectId('699e5d07d48520146b9dd607'), ObjectId('699e5d07d48520146b9dd608'), ObjectId('699e5d07d48520146b9dd609'), ObjectId('699e5d07d48520146b9dd60a'), ObjectId('699e5d07d48520146b9dd60b'), ObjectId('699e5d07d48520146b9dd60c'), ObjectId('699e5d07d48520146b9dd60d'), ObjectId('699e5d07d48520146b9dd60e'), ObjectId('699e5d07d48520146b9dd60f'), ObjectId('699e5d07d48520146b9dd610'), ObjectId('699e5d07d48520146b9dd611'), ObjectId('699e5d07d48520146b9dd612'), ObjectId('699e5d07d48520146b9dd613'), ObjectId('699e5d07d48520146b9dd614'), ObjectId('699e5d07d48520146b9dd615'), ObjectId('699e5d07d48520146b9dd616'), ObjectId('699e5d07d48520146b9dd617'), ObjectId('699e5d07d48520146b9dd618'), ObjectId('699e5d07d48520146b9dd619'), ObjectId('699e5d07d48520146b9dd61a'), ObjectId('699e5d07d48520146b9dd61b'), ObjectId('699e5d07d48520146b9dd61c'), ObjectId('699e5d07d48520146b9dd61d'), ObjectId('699e5d07d48520146b9dd61e'), ObjectId('699e5d07d48520146b9dd61f'), ObjectId('699e5d07d48520146b9dd620'), ObjectId('699e5d07d48520146b9dd621'), ObjectId('699e5d07d48520146b9dd622'), ObjectId('699e5d07d48520146b9dd623'), ObjectId('699e5d07d48520146b9dd624'), ObjectId('699e5d07d48520146b9dd625'), ObjectId('699e5d07d48520146b9dd626'), ObjectId('699e5d07d48520146b9dd627'), ObjectId('699e5d07d48520146b9dd628'), ObjectId('699e5d07d48520146b9dd629'), ObjectId('699e5d07d48520146b9dd62a'), ObjectId('699e5d07d48520146b9dd62b'), ObjectId('699e5d07d48520146b9dd62c'), ObjectId('699e5d07d48520146b9dd62d'), ObjectId('699e5d07d48520146b9dd62e'), ObjectId('699e5d07d48520146b9dd62f'), ObjectId('699e5d07d48520146b9dd630'), ObjectId('699e5d07d48520146b9dd631'), ObjectId('699e5d07d48520146b9dd632'), ObjectId('699e5d07d48520146b9dd633'), ObjectId('699e5d07d48520146b9dd634'), ObjectId('699e5d07d48520146b9dd635'), ObjectId('699e5d07d48520146b9dd636'), ObjectId('699e5d07d48520146b9dd637'), ObjectId('699e5d07d48520146b9dd638'), ObjectId('699e5d07d48520146b9dd639'), ObjectId('699e5d07d48520146b9dd63a'), ObjectId('699e5d07d48520146b9dd63b'), ObjectId('699e5d07d48520146b9dd63c'), ObjectId('699e5d07d48520146b9dd63d'), ObjectId('699e5d07d48520146b9dd63e'), ObjectId('699e5d07d48520146b9dd63f'), ObjectId('699e5d07d48520146b9dd640'), ObjectId('699e5d07d48520146b9dd641'), ObjectId('699e5d07d48520146b9dd642'), ObjectId('699e5d07d48520146b9dd643'), ObjectId('699e5d07d48520146b9dd644'), ObjectId('699e5d07d48520146b9dd645'), ObjectId('699e5d07d48520146b9dd646'), ObjectId('699e5d07d48520146b9dd647'), ObjectId('699e5d07d48520146b9dd648'), ObjectId('699e5d07d48520146b9dd649'), ObjectId('699e5d07d48520146b9dd64a'), ObjectId('699e5d07d48520146b9dd64b'), ObjectId('699e5d07d48520146b9dd64c'), ObjectId('699e5d07d48520146b9dd64d'), ObjectId('699e5d07d48520146b9dd64e'), ObjectId('699e5d07d48520146b9dd64f'), ObjectId('699e5d07d48520146b9dd650'), ObjectId('699e5d07d48520146b9dd651'), ObjectId('699e5d07d48520146b9dd652'), ObjectId('699e5d07d48520146b9dd653'), ObjectId('699e5d07d48520146b9dd654'), ObjectId('699e5d07d48520146b9dd655'), ObjectId('699e5d07d48520146b9dd656'), ObjectId('699e5d07d48520146b9dd657'), ObjectId('699e5d07d48520146b9dd658'), ObjectId('699e5d07d48520146b9dd659'), ObjectId('699e5d07d48520146b9dd65a'), ObjectId('699e5d07d48520146b9dd65b'), ObjectId('699e5d07d48520146b9dd65c'), ObjectId('699e5d07d48520146b9dd65d'), ObjectId('699e5d07d48520146b9dd65e'), ObjectId('699e5d07d48520146b9dd65f'), ObjectId('699e5d07d48520146b9dd660'), ObjectId('699e5d07d48520146b9dd661'), ObjectId('699e5d07d48520146b9dd662'), ObjectId('699e5d07d48520146b9dd663'), ObjectId('699e5d07d48520146b9dd664'), ObjectId('699e5d07d48520146b9dd665'), ObjectId('699e5d07d48520146b9dd666'), ObjectId('699e5d07d48520146b9dd667'), ObjectId('699e5d07d48520146b9dd668'), ObjectId('699e5d07d48520146b9dd669'), ObjectId('699e5d07d48520146b9dd66a'), ObjectId('699e5d07d48520146b9dd66b'), ObjectId('699e5d07d48520146b9dd66c'), ObjectId('699e5d07d48520146b9dd66d'), ObjectId('699e5d07d48520146b9dd66e'), ObjectId('699e5d07d48520146b9dd66f'), ObjectId('699e5d07d48520146b9dd670'), ObjectId('699e5d07d48520146b9dd671'), ObjectId('699e5d07d48520146b9dd672'), ObjectId('699e5d07d48520146b9dd673'), ObjectId('699e5d07d48520146b9dd674'), ObjectId('699e5d07d48520146b9dd675'), ObjectId('699e5d07d48520146b9dd676'), ObjectId('699e5d07d48520146b9dd677'), ObjectId('699e5d07d48520146b9dd678'), ObjectId('699e5d07d48520146b9dd679'), ObjectId('699e5d07d48520146b9dd67a'), ObjectId('699e5d07d48520146b9dd67b'), ObjectId('699e5d07d48520146b9dd67c'), ObjectId('699e5d07d48520146b9dd67d'), ObjectId('699e5d07d48520146b9dd67e'), ObjectId('699e5d07d48520146b9dd67f'), ObjectId('699e5d07d48520146b9dd680'), ObjectId('699e5d07d48520146b9dd681'), ObjectId('699e5d07d48520146b9dd682'), ObjectId('699e5d07d48520146b9dd683'), ObjectId('699e5d07d48520146b9dd684'), ObjectId('699e5d07d48520146b9dd685'), ObjectId('699e5d07d48520146b9dd686'), ObjectId('699e5d07d48520146b9dd687'), ObjectId('699e5d07d48520146b9dd688'), ObjectId('699e5d07d48520146b9dd689'), ObjectId('699e5d07d48520146b9dd68a'), ObjectId('699e5d07d48520146b9dd68b'), ObjectId('699e5d07d48520146b9dd68c'), ObjectId('699e5d07d48520146b9dd68d'), ObjectId('699e5d07d48520146b9dd68e'), ObjectId('699e5d07d48520146b9dd68f'), ObjectId('699e5d07d48520146b9dd690'), ObjectId('699e5d07d48520146b9dd691'), ObjectId('699e5d07d48520146b9dd692'), ObjectId('699e5d07d48520146b9dd693'), ObjectId('699e5d07d48520146b9dd694'), ObjectId('699e5d07d48520146b9dd695'), ObjectId('699e5d07d48520146b9dd696'), ObjectId('699e5d07d48520146b9dd697'), ObjectId('699e5d07d48520146b9dd698'), ObjectId('699e5d07d48520146b9dd699'), ObjectId('699e5d07d48520146b9dd69a'), ObjectId('699e5d07d48520146b9dd69b'), ObjectId('699e5d07d48520146b9dd69c'), ObjectId('699e5d07d48520146b9dd69d'), ObjectId('699e5d07d48520146b9dd69e'), ObjectId('699e5d07d48520146b9dd69f'), ObjectId('699e5d07d48520146b9dd6a0'), ObjectId('699e5d07d48520146b9dd6a1'), ObjectId('699e5d07d48520146b9dd6a2'), ObjectId('699e5d07d48520146b9dd6a3'), ObjectId('699e5d07d48520146b9dd6a4'), ObjectId('699e5d07d48520146b9dd6a5'), ObjectId('699e5d07d48520146b9dd6a6'), ObjectId('699e5d07d48520146b9dd6a7'), ObjectId('699e5d07d48520146b9dd6a8'), ObjectId('699e5d07d48520146b9dd6a9'), ObjectId('699e5d07d48520146b9dd6aa'), ObjectId('699e5d07d48520146b9dd6ab'), ObjectId('699e5d07d48520146b9dd6ac'), ObjectId('699e5d07d48520146b9dd6ad'), ObjectId('699e5d07d48520146b9dd6ae'), ObjectId('699e5d07d48520146b9dd6af'), ObjectId('699e5d07d48520146b9dd6b0'), ObjectId('699e5d07d48520146b9dd6b1'), ObjectId('699e5d07d48520146b9dd6b2'), ObjectId('699e5d07d48520146b9dd6b3'), ObjectId('699e5d07d48520146b9dd6b4'), ObjectId('699e5d07d48520146b9dd6b5'), ObjectId('699e5d07d48520146b9dd6b6'), ObjectId('699e5d07d48520146b9dd6b7'), ObjectId('699e5d07d48520146b9dd6b8'), ObjectId('699e5d07d48520146b9dd6b9'), ObjectId('699e5d07d48520146b9dd6ba'), ObjectId('699e5d07d48520146b9dd6bb'), ObjectId('699e5d07d48520146b9dd6bc'), ObjectId('699e5d07d48520146b9dd6bd'), ObjectId('699e5d07d48520146b9dd6be'), ObjectId('699e5d07d48520146b9dd6bf'), ObjectId('699e5d07d48520146b9dd6c0'), ObjectId('699e5d07d48520146b9dd6c1'), ObjectId('699e5d07d48520146b9dd6c2'), ObjectId('699e5d07d48520146b9dd6c3'), ObjectId('699e5d07d48520146b9dd6c4'), ObjectId('699e5d07d48520146b9dd6c5'), ObjectId('699e5d07d48520146b9dd6c6'), ObjectId('699e5d07d48520146b9dd6c7'), ObjectId('699e5d07d48520146b9dd6c8'), ObjectId('699e5d07d48520146b9dd6c9'), ObjectId('699e5d07d48520146b9dd6ca'), ObjectId('699e5d07d48520146b9dd6cb'), ObjectId('699e5d07d48520146b9dd6cc'), ObjectId('699e5d07d48520146b9dd6cd'), ObjectId('699e5d07d48520146b9dd6ce'), ObjectId('699e5d07d48520146b9dd6cf'), ObjectId('699e5d07d48520146b9dd6d0'), ObjectId('699e5d07d48520146b9dd6d1'), ObjectId('699e5d07d48520146b9dd6d2'), ObjectId('699e5d07d48520146b9dd6d3'), ObjectId('699e5d07d48520146b9dd6d4'), ObjectId('699e5d07d48520146b9dd6d5'), ObjectId('699e5d07d48520146b9dd6d6'), ObjectId('699e5d07d48520146b9dd6d7'), ObjectId('699e5d07d48520146b9dd6d8'), ObjectId('699e5d07d48520146b9dd6d9'), ObjectId('699e5d07d48520146b9dd6da'), ObjectId('699e5d07d48520146b9dd6db'), ObjectId('699e5d07d48520146b9dd6dc'), ObjectId('699e5d07d48520146b9dd6dd'), ObjectId('699e5d07d48520146b9dd6de'), ObjectId('699e5d07d48520146b9dd6df'), ObjectId('699e5d07d48520146b9dd6e0'), ObjectId('699e5d07d48520146b9dd6e1'), ObjectId('699e5d07d48520146b9dd6e2'), ObjectId('699e5d07d48520146b9dd6e3'), ObjectId('699e5d07d48520146b9dd6e4'), ObjectId('699e5d07d48520146b9dd6e5'), ObjectId('699e5d07d48520146b9dd6e6'), ObjectId('699e5d07d48520146b9dd6e7'), ObjectId('699e5d07d48520146b9dd6e8'), ObjectId('699e5d07d48520146b9dd6e9'), ObjectId('699e5d07d48520146b9dd6ea'), ObjectId('699e5d07d48520146b9dd6eb'), ObjectId('699e5d07d48520146b9dd6ec'), ObjectId('699e5d07d48520146b9dd6ed'), ObjectId('699e5d07d48520146b9dd6ee'), ObjectId('699e5d07d48520146b9dd6ef'), ObjectId('699e5d07d48520146b9dd6f0'), ObjectId('699e5d07d48520146b9dd6f1'), ObjectId('699e5d07d48520146b9dd6f2'), ObjectId('699e5d07d48520146b9dd6f3'), ObjectId('699e5d07d48520146b9dd6f4'), ObjectId('699e5d07d48520146b9dd6f5'), ObjectId('699e5d07d48520146b9dd6f6'), ObjectId('699e5d07d48520146b9dd6f7'), ObjectId('699e5d07d48520146b9dd6f8'), ObjectId('699e5d07d48520146b9dd6f9'), ObjectId('699e5d07d48520146b9dd6fa'), ObjectId('699e5d07d48520146b9dd6fb'), ObjectId('699e5d07d48520146b9dd6fc'), ObjectId('699e5d07d48520146b9dd6fd'), ObjectId('699e5d07d48520146b9dd6fe'), ObjectId('699e5d07d48520146b9dd6ff'), ObjectId('699e5d07d48520146b9dd700'), ObjectId('699e5d07d48520146b9dd701'), ObjectId('699e5d07d48520146b9dd702'), ObjectId('699e5d07d48520146b9dd703'), ObjectId('699e5d07d48520146b9dd704'), ObjectId('699e5d07d48520146b9dd705'), ObjectId('699e5d07d48520146b9dd706'), ObjectId('699e5d07d48520146b9dd707'), ObjectId('699e5d07d48520146b9dd708'), ObjectId('699e5d07d48520146b9dd709'), ObjectId('699e5d07d48520146b9dd70a'), ObjectId('699e5d07d48520146b9dd70b'), ObjectId('699e5d07d48520146b9dd70c'), ObjectId('699e5d07d48520146b9dd70d'), ObjectId('699e5d07d48520146b9dd70e'), ObjectId('699e5d07d48520146b9dd70f'), ObjectId('699e5d07d48520146b9dd710'), ObjectId('699e5d07d48520146b9dd711'), ObjectId('699e5d07d48520146b9dd712'), ObjectId('699e5d07d48520146b9dd713'), ObjectId('699e5d07d48520146b9dd714'), ObjectId('699e5d07d48520146b9dd715'), ObjectId('699e5d07d48520146b9dd716'), ObjectId('699e5d07d48520146b9dd717'), ObjectId('699e5d07d48520146b9dd718'), ObjectId('699e5d07d48520146b9dd719'), ObjectId('699e5d07d48520146b9dd71a'), ObjectId('699e5d07d48520146b9dd71b'), ObjectId('699e5d07d48520146b9dd71c'), ObjectId('699e5d07d48520146b9dd71d'), ObjectId('699e5d07d48520146b9dd71e'), ObjectId('699e5d07d48520146b9dd71f'), ObjectId('699e5d07d48520146b9dd720'), ObjectId('699e5d07d48520146b9dd721'), ObjectId('699e5d07d48520146b9dd722'), ObjectId('699e5d07d48520146b9dd723'), ObjectId('699e5d07d48520146b9dd724'), ObjectId('699e5d07d48520146b9dd725'), ObjectId('699e5d07d48520146b9dd726'), ObjectId('699e5d07d48520146b9dd727'), ObjectId('699e5d07d48520146b9dd728'), ObjectId('699e5d07d48520146b9dd729'), ObjectId('699e5d07d48520146b9dd72a'), ObjectId('699e5d07d48520146b9dd72b'), ObjectId('699e5d07d48520146b9dd72c'), ObjectId('699e5d07d48520146b9dd72d'), ObjectId('699e5d07d48520146b9dd72e'), ObjectId('699e5d07d48520146b9dd72f'), ObjectId('699e5d07d48520146b9dd730'), ObjectId('699e5d07d48520146b9dd731'), ObjectId('699e5d07d48520146b9dd732'), ObjectId('699e5d07d48520146b9dd733'), ObjectId('699e5d07d48520146b9dd734'), ObjectId('699e5d07d48520146b9dd735'), ObjectId('699e5d07d48520146b9dd736'), ObjectId('699e5d07d48520146b9dd737'), ObjectId('699e5d07d48520146b9dd738'), ObjectId('699e5d07d48520146b9dd739'), ObjectId('699e5d07d48520146b9dd73a'), ObjectId('699e5d07d48520146b9dd73b'), ObjectId('699e5d07d48520146b9dd73c'), ObjectId('699e5d07d48520146b9dd73d'), ObjectId('699e5d07d48520146b9dd73e'), ObjectId('699e5d07d48520146b9dd73f'), ObjectId('699e5d07d48520146b9dd740'), ObjectId('699e5d07d48520146b9dd741'), ObjectId('699e5d07d48520146b9dd742'), ObjectId('699e5d07d48520146b9dd743'), ObjectId('699e5d07d48520146b9dd744'), ObjectId('699e5d07d48520146b9dd745'), ObjectId('699e5d07d48520146b9dd746'), ObjectId('699e5d07d48520146b9dd747'), ObjectId('699e5d07d48520146b9dd748'), ObjectId('699e5d07d48520146b9dd749'), ObjectId('699e5d07d48520146b9dd74a'), ObjectId('699e5d07d48520146b9dd74b'), ObjectId('699e5d07d48520146b9dd74c'), ObjectId('699e5d07d48520146b9dd74d'), ObjectId('699e5d07d48520146b9dd74e'), ObjectId('699e5d07d48520146b9dd74f'), ObjectId('699e5d07d48520146b9dd750'), ObjectId('699e5d07d48520146b9dd751'), ObjectId('699e5d07d48520146b9dd752'), ObjectId('699e5d07d48520146b9dd753'), ObjectId('699e5d07d48520146b9dd754'), ObjectId('699e5d07d48520146b9dd755'), ObjectId('699e5d07d48520146b9dd756'), ObjectId('699e5d07d48520146b9dd757'), ObjectId('699e5d07d48520146b9dd758'), ObjectId('699e5d07d48520146b9dd759'), ObjectId('699e5d07d48520146b9dd75a'), ObjectId('699e5d07d48520146b9dd75b'), ObjectId('699e5d07d48520146b9dd75c'), ObjectId('699e5d07d48520146b9dd75d'), ObjectId('699e5d07d48520146b9dd75e'), ObjectId('699e5d07d48520146b9dd75f'), ObjectId('699e5d07d48520146b9dd760'), ObjectId('699e5d07d48520146b9dd761'), ObjectId('699e5d07d48520146b9dd762'), ObjectId('699e5d07d48520146b9dd763'), ObjectId('699e5d07d48520146b9dd764'), ObjectId('699e5d07d48520146b9dd765'), ObjectId('699e5d07d48520146b9dd766'), ObjectId('699e5d07d48520146b9dd767'), ObjectId('699e5d07d48520146b9dd768'), ObjectId('699e5d07d48520146b9dd769'), ObjectId('699e5d07d48520146b9dd76a'), ObjectId('699e5d07d48520146b9dd76b'), ObjectId('699e5d07d48520146b9dd76c'), ObjectId('699e5d07d48520146b9dd76d'), ObjectId('699e5d07d48520146b9dd76e'), ObjectId('699e5d07d48520146b9dd76f'), ObjectId('699e5d07d48520146b9dd770'), ObjectId('699e5d07d48520146b9dd771'), ObjectId('699e5d07d48520146b9dd772'), ObjectId('699e5d07d48520146b9dd773'), ObjectId('699e5d07d48520146b9dd774'), ObjectId('699e5d07d48520146b9dd775'), ObjectId('699e5d07d48520146b9dd776'), ObjectId('699e5d07d48520146b9dd777'), ObjectId('699e5d07d48520146b9dd778'), ObjectId('699e5d07d48520146b9dd779'), ObjectId('699e5d07d48520146b9dd77a'), ObjectId('699e5d07d48520146b9dd77b'), ObjectId('699e5d07d48520146b9dd77c'), ObjectId('699e5d07d48520146b9dd77d'), ObjectId('699e5d07d48520146b9dd77e'), ObjectId('699e5d07d48520146b9dd77f'), ObjectId('699e5d07d48520146b9dd780'), ObjectId('699e5d07d48520146b9dd781'), ObjectId('699e5d07d48520146b9dd782'), ObjectId('699e5d07d48520146b9dd783'), ObjectId('699e5d07d48520146b9dd784'), ObjectId('699e5d07d48520146b9dd785'), ObjectId('699e5d07d48520146b9dd786'), ObjectId('699e5d07d48520146b9dd787'), ObjectId('699e5d07d48520146b9dd788'), ObjectId('699e5d07d48520146b9dd789'), ObjectId('699e5d07d48520146b9dd78a'), ObjectId('699e5d07d48520146b9dd78b'), ObjectId('699e5d07d48520146b9dd78c'), ObjectId('699e5d07d48520146b9dd78d'), ObjectId('699e5d07d48520146b9dd78e'), ObjectId('699e5d07d48520146b9dd78f'), ObjectId('699e5d07d48520146b9dd790'), ObjectId('699e5d07d48520146b9dd791'), ObjectId('699e5d07d48520146b9dd792'), ObjectId('699e5d07d48520146b9dd793'), ObjectId('699e5d07d48520146b9dd794'), ObjectId('699e5d07d48520146b9dd795'), ObjectId('699e5d07d48520146b9dd796'), ObjectId('699e5d07d48520146b9dd797'), ObjectId('699e5d07d48520146b9dd798'), ObjectId('699e5d07d48520146b9dd799'), ObjectId('699e5d07d48520146b9dd79a'), ObjectId('699e5d07d48520146b9dd79b'), ObjectId('699e5d07d48520146b9dd79c'), ObjectId('699e5d07d48520146b9dd79d'), ObjectId('699e5d07d48520146b9dd79e'), ObjectId('699e5d07d48520146b9dd79f'), ObjectId('699e5d07d48520146b9dd7a0'), ObjectId('699e5d07d48520146b9dd7a1')], acknowledged=True)

I ran into an issue where I didn't realize some of the code from the original creation was still present, so the philippines set was cut off for players with 5 or less wins.

I can fix this in a few easy steps thanks to the pipeline refurbishing. I'll just run it again on the Manila event.

Alright, the data was successfully returned to it's litte part of the data base, now we need to run this whole thing again, or at least the philippines bits

BOOM! We're all done! The data in the central database and the isolated ones have all been updated, despite the dificulties of deleting the data of players with less than 5 wins, but we got there :)